react-form-controls
dannyandreev/rc0521-code-solutions pull request #124
Opened 2021-07-10 15:00 UTC by dannyandreev

![image](https://user-images.githubusercontent.com/82613194/125167340-dad7a480-e154-11eb-8b66-dc1b85d89a87.png)

2021-07-12 17:52 UTC, scbowler requested changes
A few updates needed. Let me know if you have any questions

2021-07-12 17:52 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +          onClick={this.handleSubmit}
`handleSubmit` should be on the `form` element on the `onSubmit` prop

2021-07-12 17:52 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +          onChange={this.handleChange}
Here you should be setting the `value` prop on the input using `state`

2021-07-12 17:52 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +    this.state = {};
Your state object should have starting values for all values in state you are going to use

2021-07-12 17:52 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +
Don't leave empty methods, if you don't use it, delete it

2021-07-12 19:45 UTC, scbowler requested changes
A few more updates needed. Let us know if you have any questions

2021-07-12 19:45 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +    this.handleClick = this.handleClick.bind(this);
There is no `handleClick` method so this shouldn't be here

2021-07-12 19:45 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +          onChange={this.handleChange}
Still need to add a `value` prop to your input

2021-07-12 19:45 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +          onSubmit={this.handleSubmit}
`handleSubmit` should be on the `form` elements `onSubmit` prop, not on the `button`

2021-07-12 22:40 UTC, scbowler requested changes
A couple more changes needed. If you are unsure on how to fix something please reach out. Also make sure to test your code after making changes.

2021-07-12 22:40 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +    this.handleClick = this.handleClick.bind(this);
Delete this line, `line 7`

2021-07-12 22:40 UTC, scbowler commented on react-form-controls/src/NewsletterForm.jsx
> +          onSubmit={this.handleSubmit}
The `onSubmit` should be on the opening `<form>` tag on line 21

2021-07-12 23:59 UTC, dannyandreev commented
![image](https://user-images.githubusercontent.com/82613194/125370073-825dfe00-e332-11eb-97d7-3e4159bbeadb.png)

2021-07-13 18:46 UTC, scbowler requested changes
This one still has the same issues as already noted. Let me know if you have any questions about the requested changes or need any clarification on any of it.

2021-07-19 18:38 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-07-20 21:58 UTC, merged