react-rendering-lists
dannyandreev/rc0521-code-solutions pull request #125
Opened 2021-07-12 18:25 UTC by dannyandreev

![image](https://user-images.githubusercontent.com/82613194/125337483-e7e6c600-e303-11eb-9b24-2f720f72cc0d.png)

2021-07-12 19:41 UTC, scbowler requested changes
A couple changes needed. Let us know if you have any questions

2021-07-12 19:41 UTC, scbowler commented on react-rendering-lists/src/index.jsx
> +      return (<li>{card.name}</li>)
Your `li` needs to have a `key` prop. You can use `card.number` to set it

2021-07-12 19:41 UTC, scbowler commented on react-rendering-lists/src/index.jsx
> +  }
Since you aren't doing anything with the `constructor` you don't need it at all here

2021-07-12 23:01 UTC, scbowler requested changes
Couple changes still needed. Let us know if you have any questions

2021-07-12 23:01 UTC, scbowler commented on react-rendering-lists/src/index.jsx
> +  }
Delete the `constructor`, it is not needed in this case

2021-07-12 23:01 UTC, scbowler commented on react-rendering-lists/src/index.jsx
> +      return (<li>{card.name}</li>)
Add a key prop to the `<li>`:

```JSX
return (<li key={card.number}>{card.name}</li>);
```

2021-07-13 00:04 UTC, dannyandreev commented
![image](https://user-images.githubusercontent.com/82613194/125370422-44150e80-e333-11eb-8b8e-00cef7fe733f.png)

2021-07-13 00:06 UTC, scbowler approved these changes
Looks good! 👍

2021-07-13 00:29 UTC, merged