express-delete
dannyandreev/rc0521-code-solutions pull request #94
Opened 2021-06-29 00:34 UTC by dannyandreev

![image](https://user-images.githubusercontent.com/82613194/123719737-25911c80-d837-11eb-81ac-909bdac786f3.png)

2021-06-29 00:47 UTC, scbowler requested changes
Some updates needed, see below comments for details. Let me know if you have any questions.

2021-06-29 00:47 UTC, scbowler commented on express-delete/index.js
> +  delete grades['12'];
You don't want to hard code the `id` here. You should be using `req.params.id` to get the `id` to delete

2021-06-29 00:47 UTC, scbowler commented on express-delete/index.js
> +
There is no need for a loop here. There should be a separate `GET` endpoint that returns the grades in an array.

2021-06-29 00:47 UTC, scbowler commented on express-delete/index.js
> +  res.send(res.params);
You can't send multiple things back from an endpoint, you can only send one thing back. And for delete you should just be sending back the status code `204`. To send back just a status code use `res.sendStatus(204)`

2021-06-29 00:47 UTC, scbowler commented on express-delete/index.js
> +
You should have a get endpoint here that returns an array of grades. Just like the one from the previous exercise.

2021-06-29 18:41 UTC, dannyandreev commented
![image](https://user-images.githubusercontent.com/82613194/123850431-e0b8c480-d8ce-11eb-9aa6-ad6aff3edcee.png)

2021-06-30 01:45 UTC, scbowler approved these changes
Great job implementing all the feedback. Looks good! 👍 

1 FYI comment, no changes required

2021-06-30 01:45 UTC, scbowler commented on express-delete/index.js
> +  res.status(204).send();
You could also use `res.sendStatus(204)` here if you are just sending a status.

2021-06-30 17:39 UTC, merged